### ISSUE TITLE
建议。可以添加转发Host吗？

### ISSUE THREAD

**Issue by fs920105** [jafshare/ComfyUI-Easy-Tools#1]
https://github.com/chatanywhere/GPT_API_free.git
我在这里找到了免费的3.5，但是密匙需要转发才能使用。
希望可以增加转发Host的功能。

**Comment by fs920105** [comment]
我找到了，原来是在设置里面。非常感谢你制作了这个节点

**Comment by jafshare** [comment]
> 我找到了，原来是在设置里面。非常感谢你制作了这个节点

感谢你的使用。这几天我会完善使用文档，很抱歉没有及时更新文档给你带来的困扰。

**Comment by fs920105** [comment]
> > 我找到了，原来是在设置里面。非常感谢你制作了这个节点
> 
> 感谢你的使用。这几天我会完善使用文档，很抱歉没有及时更新文档给你带来的困扰。

嗯，节点很不错，我也是偶然发现的使用方法。
你的这个节点不用于其他的gpt，可能是你内置的调教词很厉害，我用其他的GPT节点它老是给我返回请稍等一会，稍后我会发送给你这些无用的东西，哈哈。
但是加权重这些它好像还是不听话。所以我放弃了让GPT加权重只输出内容，重新连接了条件联结的节点专门加权重。

**Comment by jafshare** [comment]
> > > 我找到了，原来是在设置里面。非常感谢你制作了这个节点
> > 
> > 
> > 感谢你的使用。这几天我会完善使用文档，很抱歉没有及时更新文档给你带来的困扰。
> 
> 嗯，节点很不错，我也是偶然发现的使用方法。 你的这个节点不用于其他的gpt，可能是你内置的调教词很厉害，我用其他的GPT节点它老是给我返回请稍等一会，稍后我会发送给你这些无用的东西，哈哈。 但是加权重这些它好像还是不听话。所以我放弃了让GPT加权重只输出内容，重新连接了条件联结的节点专门加权重。

这个调教词我也是从其他地方借鉴的，目前还需要优化，如果你有比较好的提示词，也可以分享，后续这个节点也会开放自定义调教词的功能，可以根据自己使用的场景微调

**Comment by fs920105** [comment]
这是我五个月前收集的其中一个我感觉最有用的，其他的都太简单了。但是我不知道怎么配合好你的节点，我发给你，你看看有用没。
[prompt调试.txt](https://github.com/jafshare/ComfyUI-Easy-Tools/files/13936179/prompt.txt)

**Comment by jafshare** [comment]
> 这是我五个月前收集的其中一个我感觉最有用的，其他的都太简单了。但是我不知道怎么配合好你的节点，我发给你，你看看有用没。 [prompt调试.txt](https://github.com/jafshare/ComfyUI-Easy-Tools/files/13936179/prompt.txt)

我可以借鉴一部分内容，你的这个调教词应该是缺少了返回格式的例子，所以有时AI返回的格式达不到你的预期

**Comment by fs920105** [comment]
有用就行，期待你这个更好的调教节点，你的节点已经被这个作者翻译好了
https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues/150
![15175358](https://github.com/jafshare/ComfyUI-Easy-Tools/assets/135109872/85d03eae-b732-48f7-a3c9-86594ef769d7)
